# Generated by Django 4.2.20 on 2025-04-05 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='votingsession',
            name='election_cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='myapp.votingsession'),
        ),
        migrations.AlterField(
            model_name='classleadernomination',
            name='election_cycle',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nominations', to='myapp.votingsession'),
        ),
    ]
