# Generated by Django 4.2.20 on 2025-03-25 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_classleadernomination_finalization_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('published', 'Published')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('results_verified', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.officer')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.department')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('vote_count', models.IntegerField(default=0)),
                ('nomination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.classleadernomination')),
                ('voting_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.votingsession')),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('female_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='female_votes', to='myapp.candidate')),
                ('male_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='male_votes', to='myapp.candidate')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.student')),
                ('voting_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.votingsession')),
            ],
            options={
                'unique_together': {('student', 'voting_session')},
            },
        ),
    ]
