# Generated by Django 4.2.20 on 2025-04-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_remove_votingsession_results_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votingsession',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('active', 'Active'), ('completed', 'Completed'), ('published', 'Published'), ('cancelled', 'Cancelled')], max_length=20),
        ),
    ]
