# Generated by Django 4.2.20 on 2025-04-05 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_votingsession_results_verified_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classleadernomination',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='classleadernomination',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='classleadernomination',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classleadernomination',
            name='marks',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='CGPA on a scale of 10', max_digits=4),
        ),
        migrations.AlterField(
            model_name='classleadernomination',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classleadernomination',
            name='finalization_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='classleadernomination',
            name='nomination_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='classleadernomination',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('finalized', 'Finalized')], default='pending', max_length=20),
        ),
    ]
